name: weather_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  circle_flags: ^1.0.4
  easy_search_bar: ^2.5.0
  flutter:
    sdk: flutter
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  http: ^0.13.6
  intl: ^0.18.1
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/weather/
